### ISSUE TITLE
Missing support for multiple EventHubs in 1.1.0.RC5 (#508)

### ISSUE THREAD

**Issue by dsibilio** [microsoft/spring-cloud-azure#557]
## Missing support for multiple EventHubs in 1.1.0.RC5
I tried to backport to 1.1.0.RC5 the fix that was applied to #508 by excluding the `EventHubBinderConfiguration` (via `@SpringBootApplication(exclude=EventHubBinderConfiguration.class`) and extending it, to include the following:
```java
@Import({AzureEventHubAutoConfiguration.class, AzureEnvironmentAutoConfiguration.class})
```

as shown in commit 449a19f.

Here you can find the properties I've tried to use to make it so that the consumer bound to "_my-eh2-destination_" would consume messages coming from a 2nd EventHub (namely, *my-namespace2*), different than the default my application uses for other bindings (*default-namespace*).

```yaml
spring:
  cloud:
    azure:
      eventhub:
        enabled: true
        namespace: default-namespace
        checkpoint-storage-account: my-storage-account
      credential-file-path: my.azureauth
      resource-group: my-resource-group
      region: West US
    stream:
      default-binder: eventhub
      binders:
        eventhub2:
          type: eventhub
          spring:
            cloud:
              azure:
                eventhub:
                  enabled: true
                  connection-string: 'my-connection-string-2'
                  namespace: my-namespace-2
                  checkpoint-storage-account: my-storage-account
                  checkpoint-access-key: 'my-access-key'
                credential-file-path: my.azureauth
                resource-group: my-resource-group
                region: West US         
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    enabled: true
                    connection-string: 'my-connection-string-2'
                    namespace: my-namespace-2
                    checkpoint-storage-account: my-storage-account
                    checkpoint-access-key: 'my-access-key'
                  credential-file-path: my.azureauth
                  resource-group: my-resource-group
                  region: West US
      bindings:
        input:
          contentType: application/*+avro
          destination: my-eh2-destination
          group: $Default
          binder: eventhub2
```
(as you can see I've put a lot of extra properties in the mix, but it didn't help :) )

I've tested my Spring Boot Application with this setup and, even though the application would successfully terminate the bootstrapping process, it still didn't seem to connect to the 2nd EventHub at all (*the consumer still consumed messages coming from the first EventHub through _my-eh2-destination_, even though the binding was linked to the binder that was configured for the 2nd EventHub*).

## Questions
- Is there something else I'm missing to backport #508 into 1.1.0.RC5, that I'm not aware of?
- Is there something I'm doing wrong?
- Is there an expected date for a release that includes the #508 fix?

## Your Environment
* Version used: 1.1.0.RC5
* Operating System and version (desktop or mobile): Windows 10 Pro 64-bit
* SDK version: JDK 8u74

**Comment by neuqlz** [comment]
Hi,
Thanks for your feedback.
For q1 and q2: we will try it later, and give you a response.
For q3: according to our release trains, the next release is at Nov.

**Comment by dsibilio** [comment]
> Hi,
> Thanks for your feedback.
> For q1 and q2: we will try it later, and give you a response.
> For q3: according to our release trains, the next release is at Nov.

Thank you for the useful info.
Waiting for your feedback on q1 and q2.

**Comment by saragluna** [comment]
@dsibilio 
For question 1: 
I'm not sure whether these changes will work correctly with 1.1.0.RC5. Is it possible for you to share some codes I could check?

For question 2:
There're some extra properties in your configuration as you mentioned, and I modify your version into a workable one.

```yml
spring:
  cloud:
    azure:
      eventhub:
        checkpoint-storage-account: my-storage-account
        checkpoint-access-key: my-storage-account-access-key
        connection-string: my-eventhub-namespace-1-connection-string
    stream:
      binders:
        eventhub2:
          type: eventhub
          defaultCandidate: false       
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    connection-string: 'my-connection-string-2'
                    checkpoint-storage-account: my-storage-account
                    checkpoint-access-key: 'my-access-key'
      bindings:
        input:
          contentType: application/*+avro
          destination: my-eh2-destination
          group: $Default
          binder: eventhub2
```
As you can see I remove `credential file` related configurations because `connection string` is now the only available way as I checked the code.

I remove your `default-binder` configuration item and add the `defaultCandidate: false` one.  This configuration indicates that the `eventhub2` binder won't be considered as a default binder candidate, which if not set to false, Spring Cloud Stream will use `eventhub2` as a default binder.
