### ISSUE TITLE
Allow resources to be in different resource groups (e.g. Event Hub Namespace and Storage Account)

### ISSUE THREAD

**Issue by koenig-thomas** [microsoft/spring-cloud-azure#632]
## Expected Behavior
* It should be possible to access the resources even if they are in different resource groups. For example the EventHub Namespace is in resource group A and the Storage Account is in resource group B.
* As a bonus it would be nice to allow different locations for each resource group. But in the first step it would be sufficient to have multiple resource groups in the same location.

## Current Behavior
* The current implementation requires all resources to be in the same resource group.

## Possible Solution
* Each resource has its own "configuration block" in the application.yml. A new parameter for the resource group could be introduced.

## Steps to Reproduce (for bugs)
* -

## Snapshot Code for Reproduce 
application.yml for a single resource group (current implementation)
```yml
spring:
  cloud:
    azure:
      credential-file-path: my.azureauth
      region: West Europe
      resource-group: example-rg
      eventhub:
        namespace: example-eh-ns
        checkpoint-storage-account: example-storage
```

application.yml for multiple resource groups (a possible solution for this feature) (same location for all resource groups)
```yml
spring:
  cloud:
    azure:
      credential-file-path: my.azureauth
      region: West Europe
      eventhub:
        namespace-resource-group: example-rg-for-eh-ns
        namespace: example-eh-ns
        checkpoint-storage-account-resource-group: example-rg-for-storage
        checkpoint-storage-account: example-storage
```

## Branch
* master

## Your Environment
* Feature does not depend on OS version etc.
