### ISSUE TITLE
Spring Cloud Stream ConsumerBinding Error

### ISSUE THREAD

**Issue by saipraveenjda** [microsoft/spring-cloud-azure#716]
I am using Spring Cloud Stream Event Hub binder to consume messages from Azure Event Hub. I am facing the below error 

Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name '<topic-name>.<consumer-group>.errors.recoverer' defined in null: Cannot register bean definition [Root bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean '<topic-name>.<consumer-group>.errors.recoverer': There is already [Root bean: class [org.springframework.integration.handler.advice.ErrorMessageSendingRecoverer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.

I have a @ServiceActivator in my class to handle errors when processing using the @StreamListener. 

The binding configuration is as below

```
spring:
  cloud:
    azure:
      auto-create-resources: false
      credential-file-path: my.azureauth
      eventhub:
        checkpoint-storage-account: <storageaccount>
        namespace: <namespace>
        connection-string: <endpoint>
      region: Central US
      resource-group: azure-migration-rg
    stream:
      binders:
        default:
          defaultCandidate: true
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    checkpoint-storage-account: <storage-account>
                    namespace: <namespace1>
          type: eventhub
        eventhub2:
          defaultCandidate: false
          environment:
            spring:
              cloud:
                azure:
                  eventhub:
                    checkpoint-storage-account: <storageaccount>
                    namespace: <namespace2>
                    connection-string: <endpoint>
          type: eventhub
      bindings:
        consumer:
          binder: eventhub2
          destination: <topic-name>
          group: <consumer-group>
        producer:
          destination: <topic-name>

```
Code snippets from the Event Processor are as below

```
@StreamListener(TestMessageStreams.INGESTIONSTATUS)
  public void handleEvent(Message<?> message) throws Exception {
    // process the event
  }

@ServiceActivator(inputChannel = "<topic>.<consumergroup>.errors")
  protected void handleError(ErrorMessage errorMessage) throws Exception {
    // process Error;
  }

```
I am using the following gradle dependency
`	compile 'com.microsoft.azure:spring-cloud-azure-eventhubs-stream-binder:1.2.6'
`
Please let me know if there's something wrong/missing in the configuration/code
