### ISSUE TITLE
[Bug] Not enough information to enable health endpoint for cosmos

### ISSUE THREAD

**Issue by jialigit** [microsoft/spring-cloud-azure#939]
## Context
In the reference doc: https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/index.html#production-ready, in note about specifying the `database` to make the health endpoint work normally is lacking.

## Solution
We should add a note in the production ready section about:
To enable the health endpoint for cosmos, we have to add:
```yml
spring:
  cloud:
    azure:
      cosmos:
        database: <database>
```

this is issue is to be solved in this pr: https://github.com/hui1110/azure-dev-docs-pr/pull/11
