### ISSUE TITLE
[QUERY] Can't connect to Azure Government

### ISSUE THREAD

**Issue by diegopatinor** [microsoft/spring-cloud-azure#967]
I'm not sure if it's a question or an issue, so I'll try here first.

I have the following configuration to connect to a storage account queue in azure government

```
  cloud:
    azure:
      storage:
        queue:
          credential:
            client-id: <client-id>
            client-secret: <client-secret>
          profile:
            tenant-id: <tenant-id>
            cloud-type: AZURE_US_GOVERNMENT
            environment:
              active-directory-endpoint: https://login.microsoftonline.us
              active-directory-graph-endpoint: https://graph.microsoft.us
          endpoint: <endpoint>
```

But I am getting the following error

`Azure Identity => ERROR in getToken() call for scopes [https://storage.azure.com/.default]: AADSTS900382: Confidential Client is not supported in Cross Cloud request`

How can I change the authorization host?

The only solution I found so far is to set the following environment variable.

`AZURE_AUTHORITY_HOST=https://login.microsoftonline.us/`

I am using version 4.0.0, any suggestions?

Thanks in advance.
